In [35]:
import torch
import timm

In [41]:
input1 = torch.randn(100, 128)
input2 = torch.randn(100, 128)
cos = torch.nn.CosineSimilarity(dim=1, eps=1e-6)
output = cos(input1, input2)
print(output)
cos = torch.nn.CosineSimilarity(dim=-1, eps=1e-6)
output = cos(input1, input2)
print(output)


tensor([ 0.0431, -0.0792, -0.0695, -0.0083, -0.0329, -0.0476, -0.0608, -0.0062,
        -0.1352,  0.0507,  0.0393, -0.0700,  0.0566,  0.0351,  0.0546,  0.1161,
        -0.0254,  0.0261,  0.0806,  0.0403,  0.1141,  0.0623,  0.0563, -0.0321,
         0.0935,  0.0543, -0.1326,  0.1443, -0.0617,  0.1107, -0.1445, -0.1114,
        -0.0246,  0.0451,  0.0268,  0.1394, -0.0883, -0.0206, -0.1133,  0.0184,
        -0.1020,  0.1271, -0.0827,  0.0864, -0.0072,  0.0406, -0.1165,  0.0201,
        -0.0788,  0.0883, -0.1139, -0.0789, -0.0022,  0.1665, -0.1395, -0.0166,
        -0.0507,  0.1287, -0.0026,  0.1959, -0.0489, -0.0185,  0.0118, -0.0477,
        -0.0061,  0.2044, -0.0409,  0.0085,  0.0645,  0.0815,  0.0929, -0.0562,
        -0.0403, -0.0679, -0.0672,  0.0663, -0.1186,  0.0639,  0.0605,  0.0145,
         0.0691,  0.0070,  0.0651, -0.0388,  0.0046, -0.1074,  0.0883, -0.0038,
        -0.1208, -0.0250,  0.0443, -0.0970,  0.0139, -0.0767,  0.0970,  0.0384,
        -0.0805,  0.1366, -0.0911,  0.05

In [33]:
# def cal_attn_similaity(self, attn_list, layer_mask, cal_type='full conn'):
cal_type = 'adjacent'
cal_type='full conn'

attn_list = {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6}
print(len(attn_list))
layer_mask = [1, 0, 1, 1, 0, 1, 1]
cal_list = []
for i in range(len(attn_list)-1):
    if layer_mask[i] == 1:
        for j in range(i+1, len(attn_list)):
            if layer_mask[j] == 1:
                cal_list.append([attn_list[i], attn_list[j]])
                if cal_type == 'adjacent':
                    break
print(cal_list)

# cal_list = [([attn_list[i], attn_list[j]] if layer_mask[j]==1 else None for j in range(i+1, len(attn_list)))
#             if layer_mask[i]==1 else None for i in range(len(attn_list)-1)]
def single_out(i, j):
    global old_i
    if old_i != i:
        old_i = i
        return [i, j]
    else:
        return
    
if cal_type == 'full conn':
    cal_list = [[attn_list[i], attn_list[j]] for i in range(len(attn_list)-1) if layer_mask[i]==1 for j in range(i+1, len(attn_list)) if layer_mask[j]==1]
    print(cal_list)
else:
    old_i = -1
    cal_list = [[attn_list[i], attn_list[j]] for i in range(len(attn_list)-1) if layer_mask[i]==1 for j in range(i+1, len(attn_list)) if layer_mask[j]==1]
    cal_list = [single_out(i, j) for i, j in cal_list]
    print(cal_list)
    cal_list = [item for item in cal_list if item!=None]
    print(cal_list)




7
[[0, 2], [0, 3], [0, 5], [0, 6], [2, 3], [2, 5], [2, 6], [3, 5], [3, 6], [5, 6]]
[[0, 2], [0, 3], [0, 5], [0, 6], [2, 3], [2, 5], [2, 6], [3, 5], [3, 6], [5, 6]]


In [2]:
avail_pretrained_models = timm.list_models(pretrained=False)
len(avail_pretrained_models), avail_pretrained_models

(681,
 ['adv_inception_v3',
  'bat_resnext26ts',
  'botnet26t_256',
  'botnet50ts_256',
  'cait_m36_384',
  'cait_m48_448',
  'cait_s24_224',
  'cait_s24_384',
  'cait_s36_384',
  'cait_xs24_384',
  'cait_xxs24_224',
  'cait_xxs24_384',
  'cait_xxs36_224',
  'cait_xxs36_384',
  'coat_lite_mini',
  'coat_lite_small',
  'coat_lite_tiny',
  'coat_mini',
  'coat_tiny',
  'convit_base',
  'convit_small',
  'convit_tiny',
  'cspdarknet53',
  'cspdarknet53_iabn',
  'cspresnet50',
  'cspresnet50d',
  'cspresnet50w',
  'cspresnext50',
  'cspresnext50_iabn',
  'darknet53',
  'deit_base_distilled_patch16_224',
  'deit_base_distilled_patch16_384',
  'deit_base_patch16_224',
  'deit_base_patch16_384',
  'deit_small_distilled_patch16_224',
  'deit_small_patch16_224',
  'deit_tiny_distilled_patch16_224',
  'deit_tiny_patch16_224',
  'densenet121',
  'densenet121d',
  'densenet161',
  'densenet169',
  'densenet201',
  'densenet264',
  'densenet264d_iabn',
  'densenetblur121d',
  'diver_vit_tiny_patch1

In [3]:
model = timm.create_model('diver_vit_base_patch16_224')
x     = torch.randn(1, 3, 224, 224)
model(x).shape
print(model)

********************* This is the CHILUNG MESSAGE in DiverViT ***********************
torch.Size([1, 768])
DiverVisionTransformer(
  (patch_embed): PatchEmbed(
    (proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
    (norm): Identity()
  )
  (pos_drop): Dropout(p=0.0, inplace=False)
  (blocks): Sequential(
    (0): DiverBlock(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): DiverAttention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (attn_drop): Dropout(p=0.0, inplace=False)
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (drop_path): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop): Dropout(p=0.0, inp

In [7]:
model = timm.create_model('diver_vit_tiny_patch16_d12_h24_224')
x     = torch.randn(1, 3, 224, 224)
model(x).shape
print(model)

DiverVisionTransformer(
  (patch_embed): PatchEmbed(
    (proj): Conv2d(3, 192, kernel_size=(16, 16), stride=(16, 16))
    (norm): Identity()
  )
  (pos_drop): Dropout(p=0.0, inplace=False)
  (blocks): Sequential(
    (0): DiverBlock(
      (norm1): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
      (attn): DiverAttention(
        (qkv): Linear(in_features=192, out_features=576, bias=True)
        (attn_drop): Dropout(p=0.0, inplace=False)
        (proj): Linear(in_features=192, out_features=192, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (drop_path): Identity()
      (norm2): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=192, out_features=768, bias=True)
        (act): GELU()
        (fc2): Linear(in_features=768, out_features=192, bias=True)
        (drop): Dropout(p=0.0, inplace=False)
      )
    )
    (1): DiverBlock(
      (norm1): LayerNorm((192,), eps=1e-06, elementwise_affine=

In [13]:
print(model.patch_embed)
for id, i in enumerate(model.blocks):
    print('block {}'.format(id))
    print(i)

PatchEmbed(
  (proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
  (norm): Identity()
)
block 0
DiverBlock(
  (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
  (attn): DiverAttention(
    (qkv): Linear(in_features=768, out_features=2304, bias=True)
    (attn_drop): Dropout(p=0.0, inplace=False)
    (proj): Linear(in_features=768, out_features=768, bias=True)
    (proj_drop): Dropout(p=0.0, inplace=False)
  )
  (drop_path): Identity()
  (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
  (mlp): Mlp(
    (fc1): Linear(in_features=768, out_features=3072, bias=True)
    (act): GELU()
    (fc2): Linear(in_features=3072, out_features=768, bias=True)
    (drop): Dropout(p=0.0, inplace=False)
  )
)
block 1
DiverBlock(
  (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
  (attn): DiverAttention(
    (qkv): Linear(in_features=768, out_features=2304, bias=True)
    (attn_drop): Dropout(p=0.0, inplace=False)
    (proj): Linear(in_features=768, ou

https://github.com/jeonsworld/ViT-pytorch/blob/main/visualize_attention_map.ipynb

https://pytorch.org/docs/stable/generated/torch.nn.modules.module.register_module_forward_hook.html

# Visualize feature maps
activation = {}
def get_activation(name):
    def hook(model, input, output):
        activation[name] = output.detach()
    return hook

model.conv1.register_forward_hook(get_activation('conv1'))
data, _ = dataset[0]
data.unsqueeze_(0)
output = model(data)

act = activation['conv1'].squeeze()
fig, axarr = plt.subplots(act.size(0))
for idx in range(act.size(0)):
    axarr[idx].imshow(act[idx])

model = models.resnet18()

outputs = []
def hook(module, input, output):
    outputs.append(output)

model.layer2.conv1.register_forward_hook (hook

In [13]:
import numpy as np

# A是array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
A = np.arange(16)

# 将A变换为三维矩阵
A = A.reshape(4,4)
print(A)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [23]:
A = A.transpose(-3,-2)
print(A)

AxisError: axis -3 is out of bounds for array of dimension 2

In [30]:
import collections.abc
from itertools import repeat

def _ntuple(n):
    def parse(x):
        if isinstance(x, collections.abc.Iterable):
            return x
        return tuple(repeat(x, n))
    return parse


to_1tuple = _ntuple(1)
to_2tuple = _ntuple(3)

print(to_2tuple(224))

(224, 224, 224)


In [34]:
import torch
dpr = [x.item() for x in torch.linspace(0, 6, 10)]
print(dpr)
dpr = [x for x in torch.linspace(0, 6, 10)]
print(dpr)

[0.0, 0.6666666865348816, 1.3333333730697632, 2.0, 2.6666667461395264, 3.3333332538604736, 4.0, 4.666666507720947, 5.333333492279053, 6.0]
[tensor(0.), tensor(0.6667), tensor(1.3333), tensor(2.), tensor(2.6667), tensor(3.3333), tensor(4.), tensor(4.6667), tensor(5.3333), tensor(6.)]


In [29]:
import time

for head in (3, 6, 12, 24, 48, 96):
    
    shape = (196, 1920,)
    Q = torch.rand(shape)
    Q = Q.reshape(shape[0], head, shape[1]//head).permute(1, 0, 2)
    print(Q.size())

    K = torch.rand(shape)
    K = K.reshape(shape[0], head, shape[1]//head).permute(1, 0, 2)
    print(K.size())
    print(K.transpose(-2, -1).size())

    start = time.time()
    for i in range(10000):
        C = Q @ K.transpose(-2, -1)
    end = time.time()
    print(shape[0]*shape[0]*shape[1]/head)
    print(end-start)

torch.Size([3, 196, 640])
torch.Size([3, 196, 640])
torch.Size([3, 640, 196])
24586240.0
1.9709486961364746
torch.Size([6, 196, 320])
torch.Size([6, 196, 320])
torch.Size([6, 320, 196])
12293120.0
1.3969080448150635
torch.Size([12, 196, 160])
torch.Size([12, 196, 160])
torch.Size([12, 160, 196])
6146560.0
0.9893898963928223
torch.Size([24, 196, 80])
torch.Size([24, 196, 80])
torch.Size([24, 80, 196])
3073280.0
0.8741466999053955
torch.Size([48, 196, 40])
torch.Size([48, 196, 40])
torch.Size([48, 40, 196])
1536640.0
0.8224117755889893
torch.Size([96, 196, 20])
torch.Size([96, 196, 20])
torch.Size([96, 20, 196])
768320.0
0.9044473171234131
